version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - client
  